GET http://localhost:4000
Content-Type: application/json

###

GET http://localhost:4000/peter
Content-Type: application/json

###


GET http://localhost:4000/blogs
Content-Type: application/json

###


GET http://localhost:4000/blogs/5fbd7a63477a83e3bd9da488
Content-Type: application/json

###
POST http://localhost:4000/blogs
Content-Type: application/json

{
  "title":"My 10 blog",
  "description":"This is a short 10 blog",
  "mainBody":"Here is the main body content of the 10 blog",
  "date":"2020-11-17"
}

###

PUT http://localhost:4000/blogs
Content-Type: application/json

###

GET http://localhost:4000/blogs/tom
Content-Type: application/json

###

DELETE http://localhost:4000/blogs/5fbe3ca5d1955ff22b24624f
Content-Type: application/json
